// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: cproto.proto
// Protobuf C++ Version: 5.29.3

#include "cproto.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr ResponseEnvelope::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : payload_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        error_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        id_{static_cast< ::ID >(0)},
        status_{false},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ResponseEnvelope::ResponseEnvelope(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ResponseEnvelopeDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ResponseEnvelopeDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ResponseEnvelopeDefaultTypeInternal() {}
  union {
    ResponseEnvelope _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ResponseEnvelopeDefaultTypeInternal _ResponseEnvelope_default_instance_;

inline constexpr RequestEnvelope::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : payload_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        id_{static_cast< ::ID >(0)},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR RequestEnvelope::RequestEnvelope(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct RequestEnvelopeDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RequestEnvelopeDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RequestEnvelopeDefaultTypeInternal() {}
  union {
    RequestEnvelope _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RequestEnvelopeDefaultTypeInternal _RequestEnvelope_default_instance_;

inline constexpr LoadSolutionRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : context_{},
        solution_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR LoadSolutionRequest::LoadSolutionRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct LoadSolutionRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR LoadSolutionRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~LoadSolutionRequestDefaultTypeInternal() {}
  union {
    LoadSolutionRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 LoadSolutionRequestDefaultTypeInternal _LoadSolutionRequest_default_instance_;

inline constexpr ListComponentsResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : component_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ListComponentsResponse::ListComponentsResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ListComponentsResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ListComponentsResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ListComponentsResponseDefaultTypeInternal() {}
  union {
    ListComponentsResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ListComponentsResponseDefaultTypeInternal _ListComponentsResponse_default_instance_;

inline constexpr GetVersionResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : version_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR GetVersionResponse::GetVersionResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct GetVersionResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GetVersionResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~GetVersionResponseDefaultTypeInternal() {}
  union {
    GetVersionResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GetVersionResponseDefaultTypeInternal _GetVersionResponse_default_instance_;
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_cproto_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_cproto_2eproto = nullptr;
const ::uint32_t
    TableStruct_cproto_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::RequestEnvelope, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::RequestEnvelope, _impl_.id_),
        PROTOBUF_FIELD_OFFSET(::RequestEnvelope, _impl_.payload_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::ResponseEnvelope, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::ResponseEnvelope, _impl_.id_),
        PROTOBUF_FIELD_OFFSET(::ResponseEnvelope, _impl_.status_),
        PROTOBUF_FIELD_OFFSET(::ResponseEnvelope, _impl_.payload_),
        PROTOBUF_FIELD_OFFSET(::ResponseEnvelope, _impl_.error_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::GetVersionResponse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::GetVersionResponse, _impl_.version_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::LoadSolutionRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::LoadSolutionRequest, _impl_.solution_),
        PROTOBUF_FIELD_OFFSET(::LoadSolutionRequest, _impl_.context_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::ListComponentsResponse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::ListComponentsResponse, _impl_.component_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::RequestEnvelope)},
        {10, -1, -1, sizeof(::ResponseEnvelope)},
        {22, -1, -1, sizeof(::GetVersionResponse)},
        {31, -1, -1, sizeof(::LoadSolutionRequest)},
        {41, -1, -1, sizeof(::ListComponentsResponse)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::_RequestEnvelope_default_instance_._instance,
    &::_ResponseEnvelope_default_instance_._instance,
    &::_GetVersionResponse_default_instance_._instance,
    &::_LoadSolutionRequest_default_instance_._instance,
    &::_ListComponentsResponse_default_instance_._instance,
};
const char descriptor_table_protodef_cproto_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\014cproto.proto\"3\n\017RequestEnvelope\022\017\n\002id\030"
    "\001 \001(\0162\003.ID\022\017\n\007payload\030\002 \001(\014\"S\n\020ResponseE"
    "nvelope\022\017\n\002id\030\001 \001(\0162\003.ID\022\016\n\006status\030\003 \001(\010"
    "\022\017\n\007payload\030\002 \001(\014\022\r\n\005error\030\004 \001(\t\"%\n\022GetV"
    "ersionResponse\022\017\n\007version\030\001 \001(\t\"8\n\023LoadS"
    "olutionRequest\022\020\n\010solution\030\001 \001(\t\022\017\n\007cont"
    "ext\030\002 \003(\t\"+\n\026ListComponentsResponse\022\021\n\tc"
    "omponent\030\001 \003(\t*e\n\002ID\022\010\n\004NONE\020\000\022\014\n\010SHUTDO"
    "WN\020\001\022\017\n\013GET_VERSION\020\002\022\016\n\nLOAD_PACKS\020\003\022\021\n"
    "\rLOAD_SOLUTION\020\004\022\023\n\017LIST_COMPONENTS\020\005b\006p"
    "roto3"
};
static ::absl::once_flag descriptor_table_cproto_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_cproto_2eproto = {
    false,
    false,
    405,
    descriptor_table_protodef_cproto_2eproto,
    "cproto.proto",
    &descriptor_table_cproto_2eproto_once,
    nullptr,
    0,
    5,
    schemas,
    file_default_instances,
    TableStruct_cproto_2eproto::offsets,
    file_level_enum_descriptors_cproto_2eproto,
    file_level_service_descriptors_cproto_2eproto,
};
const ::google::protobuf::EnumDescriptor* ID_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_cproto_2eproto);
  return file_level_enum_descriptors_cproto_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t ID_internal_data_[] = {
    393216u, 0u, };
bool ID_IsValid(int value) {
  return 0 <= value && value <= 5;
}
// ===================================================================

class RequestEnvelope::_Internal {
 public:
};

RequestEnvelope::RequestEnvelope(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:RequestEnvelope)
}
inline PROTOBUF_NDEBUG_INLINE RequestEnvelope::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::RequestEnvelope& from_msg)
      : payload_(arena, from.payload_),
        _cached_size_{0} {}

RequestEnvelope::RequestEnvelope(
    ::google::protobuf::Arena* arena,
    const RequestEnvelope& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  RequestEnvelope* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.id_ = from._impl_.id_;

  // @@protoc_insertion_point(copy_constructor:RequestEnvelope)
}
inline PROTOBUF_NDEBUG_INLINE RequestEnvelope::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : payload_(arena),
        _cached_size_{0} {}

inline void RequestEnvelope::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.id_ = {};
}
RequestEnvelope::~RequestEnvelope() {
  // @@protoc_insertion_point(destructor:RequestEnvelope)
  SharedDtor(*this);
}
inline void RequestEnvelope::SharedDtor(MessageLite& self) {
  RequestEnvelope& this_ = static_cast<RequestEnvelope&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.payload_.Destroy();
  this_._impl_.~Impl_();
}

inline void* RequestEnvelope::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) RequestEnvelope(arena);
}
constexpr auto RequestEnvelope::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(RequestEnvelope),
                                            alignof(RequestEnvelope));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull RequestEnvelope::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_RequestEnvelope_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &RequestEnvelope::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<RequestEnvelope>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &RequestEnvelope::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<RequestEnvelope>(), &RequestEnvelope::ByteSizeLong,
            &RequestEnvelope::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(RequestEnvelope, _impl_._cached_size_),
        false,
    },
    &RequestEnvelope::kDescriptorMethods,
    &descriptor_table_cproto_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* RequestEnvelope::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2> RequestEnvelope::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::RequestEnvelope>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // bytes payload = 2;
    {::_pbi::TcParser::FastBS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(RequestEnvelope, _impl_.payload_)}},
    // .ID id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(RequestEnvelope, _impl_.id_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(RequestEnvelope, _impl_.id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .ID id = 1;
    {PROTOBUF_FIELD_OFFSET(RequestEnvelope, _impl_.id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
    // bytes payload = 2;
    {PROTOBUF_FIELD_OFFSET(RequestEnvelope, _impl_.payload_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBytes | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void RequestEnvelope::Clear() {
// @@protoc_insertion_point(message_clear_start:RequestEnvelope)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.payload_.ClearToEmpty();
  _impl_.id_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* RequestEnvelope::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const RequestEnvelope& this_ = static_cast<const RequestEnvelope&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* RequestEnvelope::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const RequestEnvelope& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:RequestEnvelope)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // .ID id = 1;
          if (this_._internal_id() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteEnumToArray(
                1, this_._internal_id(), target);
          }

          // bytes payload = 2;
          if (!this_._internal_payload().empty()) {
            const std::string& _s = this_._internal_payload();
            target = stream->WriteBytesMaybeAliased(2, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:RequestEnvelope)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t RequestEnvelope::ByteSizeLong(const MessageLite& base) {
          const RequestEnvelope& this_ = static_cast<const RequestEnvelope&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t RequestEnvelope::ByteSizeLong() const {
          const RequestEnvelope& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:RequestEnvelope)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // bytes payload = 2;
            if (!this_._internal_payload().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                              this_._internal_payload());
            }
            // .ID id = 1;
            if (this_._internal_id() != 0) {
              total_size += 1 +
                            ::_pbi::WireFormatLite::EnumSize(this_._internal_id());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void RequestEnvelope::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<RequestEnvelope*>(&to_msg);
  auto& from = static_cast<const RequestEnvelope&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:RequestEnvelope)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_payload().empty()) {
    _this->_internal_set_payload(from._internal_payload());
  }
  if (from._internal_id() != 0) {
    _this->_impl_.id_ = from._impl_.id_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void RequestEnvelope::CopyFrom(const RequestEnvelope& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:RequestEnvelope)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void RequestEnvelope::InternalSwap(RequestEnvelope* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.payload_, &other->_impl_.payload_, arena);
  swap(_impl_.id_, other->_impl_.id_);
}

::google::protobuf::Metadata RequestEnvelope::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class ResponseEnvelope::_Internal {
 public:
};

ResponseEnvelope::ResponseEnvelope(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:ResponseEnvelope)
}
inline PROTOBUF_NDEBUG_INLINE ResponseEnvelope::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::ResponseEnvelope& from_msg)
      : payload_(arena, from.payload_),
        error_(arena, from.error_),
        _cached_size_{0} {}

ResponseEnvelope::ResponseEnvelope(
    ::google::protobuf::Arena* arena,
    const ResponseEnvelope& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ResponseEnvelope* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, id_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, id_),
           offsetof(Impl_, status_) -
               offsetof(Impl_, id_) +
               sizeof(Impl_::status_));

  // @@protoc_insertion_point(copy_constructor:ResponseEnvelope)
}
inline PROTOBUF_NDEBUG_INLINE ResponseEnvelope::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : payload_(arena),
        error_(arena),
        _cached_size_{0} {}

inline void ResponseEnvelope::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, id_),
           0,
           offsetof(Impl_, status_) -
               offsetof(Impl_, id_) +
               sizeof(Impl_::status_));
}
ResponseEnvelope::~ResponseEnvelope() {
  // @@protoc_insertion_point(destructor:ResponseEnvelope)
  SharedDtor(*this);
}
inline void ResponseEnvelope::SharedDtor(MessageLite& self) {
  ResponseEnvelope& this_ = static_cast<ResponseEnvelope&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.payload_.Destroy();
  this_._impl_.error_.Destroy();
  this_._impl_.~Impl_();
}

inline void* ResponseEnvelope::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) ResponseEnvelope(arena);
}
constexpr auto ResponseEnvelope::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(ResponseEnvelope),
                                            alignof(ResponseEnvelope));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull ResponseEnvelope::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_ResponseEnvelope_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &ResponseEnvelope::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<ResponseEnvelope>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &ResponseEnvelope::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<ResponseEnvelope>(), &ResponseEnvelope::ByteSizeLong,
            &ResponseEnvelope::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(ResponseEnvelope, _impl_._cached_size_),
        false,
    },
    &ResponseEnvelope::kDescriptorMethods,
    &descriptor_table_cproto_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* ResponseEnvelope::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 0, 30, 2> ResponseEnvelope::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::ResponseEnvelope>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string error = 4;
    {::_pbi::TcParser::FastUS1,
     {34, 63, 0, PROTOBUF_FIELD_OFFSET(ResponseEnvelope, _impl_.error_)}},
    // .ID id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ResponseEnvelope, _impl_.id_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(ResponseEnvelope, _impl_.id_)}},
    // bytes payload = 2;
    {::_pbi::TcParser::FastBS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(ResponseEnvelope, _impl_.payload_)}},
    // bool status = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(ResponseEnvelope, _impl_.status_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(ResponseEnvelope, _impl_.status_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .ID id = 1;
    {PROTOBUF_FIELD_OFFSET(ResponseEnvelope, _impl_.id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
    // bytes payload = 2;
    {PROTOBUF_FIELD_OFFSET(ResponseEnvelope, _impl_.payload_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBytes | ::_fl::kRepAString)},
    // bool status = 3;
    {PROTOBUF_FIELD_OFFSET(ResponseEnvelope, _impl_.status_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // string error = 4;
    {PROTOBUF_FIELD_OFFSET(ResponseEnvelope, _impl_.error_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\20\0\0\0\5\0\0\0"
    "ResponseEnvelope"
    "error"
  }},
};

PROTOBUF_NOINLINE void ResponseEnvelope::Clear() {
// @@protoc_insertion_point(message_clear_start:ResponseEnvelope)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.payload_.ClearToEmpty();
  _impl_.error_.ClearToEmpty();
  ::memset(&_impl_.id_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.status_) -
      reinterpret_cast<char*>(&_impl_.id_)) + sizeof(_impl_.status_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* ResponseEnvelope::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const ResponseEnvelope& this_ = static_cast<const ResponseEnvelope&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* ResponseEnvelope::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const ResponseEnvelope& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:ResponseEnvelope)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // .ID id = 1;
          if (this_._internal_id() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteEnumToArray(
                1, this_._internal_id(), target);
          }

          // bytes payload = 2;
          if (!this_._internal_payload().empty()) {
            const std::string& _s = this_._internal_payload();
            target = stream->WriteBytesMaybeAliased(2, _s, target);
          }

          // bool status = 3;
          if (this_._internal_status() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                3, this_._internal_status(), target);
          }

          // string error = 4;
          if (!this_._internal_error().empty()) {
            const std::string& _s = this_._internal_error();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "ResponseEnvelope.error");
            target = stream->WriteStringMaybeAliased(4, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:ResponseEnvelope)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t ResponseEnvelope::ByteSizeLong(const MessageLite& base) {
          const ResponseEnvelope& this_ = static_cast<const ResponseEnvelope&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t ResponseEnvelope::ByteSizeLong() const {
          const ResponseEnvelope& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:ResponseEnvelope)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // bytes payload = 2;
            if (!this_._internal_payload().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                              this_._internal_payload());
            }
            // string error = 4;
            if (!this_._internal_error().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_error());
            }
            // .ID id = 1;
            if (this_._internal_id() != 0) {
              total_size += 1 +
                            ::_pbi::WireFormatLite::EnumSize(this_._internal_id());
            }
            // bool status = 3;
            if (this_._internal_status() != 0) {
              total_size += 2;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void ResponseEnvelope::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ResponseEnvelope*>(&to_msg);
  auto& from = static_cast<const ResponseEnvelope&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ResponseEnvelope)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_payload().empty()) {
    _this->_internal_set_payload(from._internal_payload());
  }
  if (!from._internal_error().empty()) {
    _this->_internal_set_error(from._internal_error());
  }
  if (from._internal_id() != 0) {
    _this->_impl_.id_ = from._impl_.id_;
  }
  if (from._internal_status() != 0) {
    _this->_impl_.status_ = from._impl_.status_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ResponseEnvelope::CopyFrom(const ResponseEnvelope& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ResponseEnvelope)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ResponseEnvelope::InternalSwap(ResponseEnvelope* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.payload_, &other->_impl_.payload_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.error_, &other->_impl_.error_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ResponseEnvelope, _impl_.status_)
      + sizeof(ResponseEnvelope::_impl_.status_)
      - PROTOBUF_FIELD_OFFSET(ResponseEnvelope, _impl_.id_)>(
          reinterpret_cast<char*>(&_impl_.id_),
          reinterpret_cast<char*>(&other->_impl_.id_));
}

::google::protobuf::Metadata ResponseEnvelope::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class GetVersionResponse::_Internal {
 public:
};

GetVersionResponse::GetVersionResponse(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:GetVersionResponse)
}
inline PROTOBUF_NDEBUG_INLINE GetVersionResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::GetVersionResponse& from_msg)
      : version_(arena, from.version_),
        _cached_size_{0} {}

GetVersionResponse::GetVersionResponse(
    ::google::protobuf::Arena* arena,
    const GetVersionResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  GetVersionResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:GetVersionResponse)
}
inline PROTOBUF_NDEBUG_INLINE GetVersionResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : version_(arena),
        _cached_size_{0} {}

inline void GetVersionResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
GetVersionResponse::~GetVersionResponse() {
  // @@protoc_insertion_point(destructor:GetVersionResponse)
  SharedDtor(*this);
}
inline void GetVersionResponse::SharedDtor(MessageLite& self) {
  GetVersionResponse& this_ = static_cast<GetVersionResponse&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.version_.Destroy();
  this_._impl_.~Impl_();
}

inline void* GetVersionResponse::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) GetVersionResponse(arena);
}
constexpr auto GetVersionResponse::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(GetVersionResponse),
                                            alignof(GetVersionResponse));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull GetVersionResponse::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_GetVersionResponse_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &GetVersionResponse::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<GetVersionResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &GetVersionResponse::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<GetVersionResponse>(), &GetVersionResponse::ByteSizeLong,
            &GetVersionResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(GetVersionResponse, _impl_._cached_size_),
        false,
    },
    &GetVersionResponse::kDescriptorMethods,
    &descriptor_table_cproto_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* GetVersionResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 34, 2> GetVersionResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::GetVersionResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string version = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(GetVersionResponse, _impl_.version_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string version = 1;
    {PROTOBUF_FIELD_OFFSET(GetVersionResponse, _impl_.version_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\22\7\0\0\0\0\0\0"
    "GetVersionResponse"
    "version"
  }},
};

PROTOBUF_NOINLINE void GetVersionResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:GetVersionResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.version_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* GetVersionResponse::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const GetVersionResponse& this_ = static_cast<const GetVersionResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* GetVersionResponse::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const GetVersionResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:GetVersionResponse)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string version = 1;
          if (!this_._internal_version().empty()) {
            const std::string& _s = this_._internal_version();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "GetVersionResponse.version");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:GetVersionResponse)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t GetVersionResponse::ByteSizeLong(const MessageLite& base) {
          const GetVersionResponse& this_ = static_cast<const GetVersionResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t GetVersionResponse::ByteSizeLong() const {
          const GetVersionResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:GetVersionResponse)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // string version = 1;
            if (!this_._internal_version().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_version());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void GetVersionResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<GetVersionResponse*>(&to_msg);
  auto& from = static_cast<const GetVersionResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:GetVersionResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_version().empty()) {
    _this->_internal_set_version(from._internal_version());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void GetVersionResponse::CopyFrom(const GetVersionResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:GetVersionResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void GetVersionResponse::InternalSwap(GetVersionResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.version_, &other->_impl_.version_, arena);
}

::google::protobuf::Metadata GetVersionResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class LoadSolutionRequest::_Internal {
 public:
};

LoadSolutionRequest::LoadSolutionRequest(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:LoadSolutionRequest)
}
inline PROTOBUF_NDEBUG_INLINE LoadSolutionRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::LoadSolutionRequest& from_msg)
      : context_{visibility, arena, from.context_},
        solution_(arena, from.solution_),
        _cached_size_{0} {}

LoadSolutionRequest::LoadSolutionRequest(
    ::google::protobuf::Arena* arena,
    const LoadSolutionRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  LoadSolutionRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:LoadSolutionRequest)
}
inline PROTOBUF_NDEBUG_INLINE LoadSolutionRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : context_{visibility, arena},
        solution_(arena),
        _cached_size_{0} {}

inline void LoadSolutionRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
LoadSolutionRequest::~LoadSolutionRequest() {
  // @@protoc_insertion_point(destructor:LoadSolutionRequest)
  SharedDtor(*this);
}
inline void LoadSolutionRequest::SharedDtor(MessageLite& self) {
  LoadSolutionRequest& this_ = static_cast<LoadSolutionRequest&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.solution_.Destroy();
  this_._impl_.~Impl_();
}

inline void* LoadSolutionRequest::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) LoadSolutionRequest(arena);
}
constexpr auto LoadSolutionRequest::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(LoadSolutionRequest, _impl_.context_) +
          decltype(LoadSolutionRequest::_impl_.context_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::CopyInit(
        sizeof(LoadSolutionRequest), alignof(LoadSolutionRequest), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&LoadSolutionRequest::PlacementNew_,
                                 sizeof(LoadSolutionRequest),
                                 alignof(LoadSolutionRequest));
  }
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull LoadSolutionRequest::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_LoadSolutionRequest_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &LoadSolutionRequest::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<LoadSolutionRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &LoadSolutionRequest::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<LoadSolutionRequest>(), &LoadSolutionRequest::ByteSizeLong,
            &LoadSolutionRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(LoadSolutionRequest, _impl_._cached_size_),
        false,
    },
    &LoadSolutionRequest::kDescriptorMethods,
    &descriptor_table_cproto_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* LoadSolutionRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 43, 2> LoadSolutionRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::LoadSolutionRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated string context = 2;
    {::_pbi::TcParser::FastUR1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(LoadSolutionRequest, _impl_.context_)}},
    // string solution = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(LoadSolutionRequest, _impl_.solution_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string solution = 1;
    {PROTOBUF_FIELD_OFFSET(LoadSolutionRequest, _impl_.solution_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // repeated string context = 2;
    {PROTOBUF_FIELD_OFFSET(LoadSolutionRequest, _impl_.context_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kUtf8String | ::_fl::kRepSString)},
  }},
  // no aux_entries
  {{
    "\23\10\7\0\0\0\0\0"
    "LoadSolutionRequest"
    "solution"
    "context"
  }},
};

PROTOBUF_NOINLINE void LoadSolutionRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:LoadSolutionRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.context_.Clear();
  _impl_.solution_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* LoadSolutionRequest::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const LoadSolutionRequest& this_ = static_cast<const LoadSolutionRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* LoadSolutionRequest::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const LoadSolutionRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:LoadSolutionRequest)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string solution = 1;
          if (!this_._internal_solution().empty()) {
            const std::string& _s = this_._internal_solution();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "LoadSolutionRequest.solution");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // repeated string context = 2;
          for (int i = 0, n = this_._internal_context_size(); i < n; ++i) {
            const auto& s = this_._internal_context().Get(i);
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                s.data(), static_cast<int>(s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "LoadSolutionRequest.context");
            target = stream->WriteString(2, s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:LoadSolutionRequest)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t LoadSolutionRequest::ByteSizeLong(const MessageLite& base) {
          const LoadSolutionRequest& this_ = static_cast<const LoadSolutionRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t LoadSolutionRequest::ByteSizeLong() const {
          const LoadSolutionRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:LoadSolutionRequest)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated string context = 2;
            {
              total_size +=
                  1 * ::google::protobuf::internal::FromIntSize(this_._internal_context().size());
              for (int i = 0, n = this_._internal_context().size(); i < n; ++i) {
                total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
                    this_._internal_context().Get(i));
              }
            }
          }
           {
            // string solution = 1;
            if (!this_._internal_solution().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_solution());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void LoadSolutionRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<LoadSolutionRequest*>(&to_msg);
  auto& from = static_cast<const LoadSolutionRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:LoadSolutionRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_context()->MergeFrom(from._internal_context());
  if (!from._internal_solution().empty()) {
    _this->_internal_set_solution(from._internal_solution());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void LoadSolutionRequest::CopyFrom(const LoadSolutionRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:LoadSolutionRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void LoadSolutionRequest::InternalSwap(LoadSolutionRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.context_.InternalSwap(&other->_impl_.context_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.solution_, &other->_impl_.solution_, arena);
}

::google::protobuf::Metadata LoadSolutionRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class ListComponentsResponse::_Internal {
 public:
};

ListComponentsResponse::ListComponentsResponse(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:ListComponentsResponse)
}
inline PROTOBUF_NDEBUG_INLINE ListComponentsResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::ListComponentsResponse& from_msg)
      : component_{visibility, arena, from.component_},
        _cached_size_{0} {}

ListComponentsResponse::ListComponentsResponse(
    ::google::protobuf::Arena* arena,
    const ListComponentsResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ListComponentsResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:ListComponentsResponse)
}
inline PROTOBUF_NDEBUG_INLINE ListComponentsResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : component_{visibility, arena},
        _cached_size_{0} {}

inline void ListComponentsResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
ListComponentsResponse::~ListComponentsResponse() {
  // @@protoc_insertion_point(destructor:ListComponentsResponse)
  SharedDtor(*this);
}
inline void ListComponentsResponse::SharedDtor(MessageLite& self) {
  ListComponentsResponse& this_ = static_cast<ListComponentsResponse&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* ListComponentsResponse::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) ListComponentsResponse(arena);
}
constexpr auto ListComponentsResponse::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(ListComponentsResponse, _impl_.component_) +
          decltype(ListComponentsResponse::_impl_.component_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(ListComponentsResponse), alignof(ListComponentsResponse), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&ListComponentsResponse::PlacementNew_,
                                 sizeof(ListComponentsResponse),
                                 alignof(ListComponentsResponse));
  }
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull ListComponentsResponse::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_ListComponentsResponse_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &ListComponentsResponse::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<ListComponentsResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &ListComponentsResponse::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<ListComponentsResponse>(), &ListComponentsResponse::ByteSizeLong,
            &ListComponentsResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(ListComponentsResponse, _impl_._cached_size_),
        false,
    },
    &ListComponentsResponse::kDescriptorMethods,
    &descriptor_table_cproto_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* ListComponentsResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 40, 2> ListComponentsResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::ListComponentsResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated string component = 1;
    {::_pbi::TcParser::FastUR1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(ListComponentsResponse, _impl_.component_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated string component = 1;
    {PROTOBUF_FIELD_OFFSET(ListComponentsResponse, _impl_.component_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kUtf8String | ::_fl::kRepSString)},
  }},
  // no aux_entries
  {{
    "\26\11\0\0\0\0\0\0"
    "ListComponentsResponse"
    "component"
  }},
};

PROTOBUF_NOINLINE void ListComponentsResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:ListComponentsResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.component_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* ListComponentsResponse::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const ListComponentsResponse& this_ = static_cast<const ListComponentsResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* ListComponentsResponse::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const ListComponentsResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:ListComponentsResponse)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // repeated string component = 1;
          for (int i = 0, n = this_._internal_component_size(); i < n; ++i) {
            const auto& s = this_._internal_component().Get(i);
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                s.data(), static_cast<int>(s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "ListComponentsResponse.component");
            target = stream->WriteString(1, s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:ListComponentsResponse)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t ListComponentsResponse::ByteSizeLong(const MessageLite& base) {
          const ListComponentsResponse& this_ = static_cast<const ListComponentsResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t ListComponentsResponse::ByteSizeLong() const {
          const ListComponentsResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:ListComponentsResponse)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated string component = 1;
            {
              total_size +=
                  1 * ::google::protobuf::internal::FromIntSize(this_._internal_component().size());
              for (int i = 0, n = this_._internal_component().size(); i < n; ++i) {
                total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
                    this_._internal_component().Get(i));
              }
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void ListComponentsResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ListComponentsResponse*>(&to_msg);
  auto& from = static_cast<const ListComponentsResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ListComponentsResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_component()->MergeFrom(from._internal_component());
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ListComponentsResponse::CopyFrom(const ListComponentsResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ListComponentsResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ListComponentsResponse::InternalSwap(ListComponentsResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.component_.InternalSwap(&other->_impl_.component_);
}

::google::protobuf::Metadata ListComponentsResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_cproto_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
